FROM node:21@sha256:b9ccc4aca32eebf124e0ca0fd573dacffba2b9236987a1d4d2625ce3c162ecc8 AS build

# via https://pnpm.io/docker
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY package.json pnpm-lock.yaml /app/
WORKDIR /app

RUN \
	--mount=type=cache,id=pnpm,target=/pnpm/store \
	pnpm install --frozen-lockfile

# Pre-fixups
RUN <<EOS
#!/bin/bash

set -euxo pipefail

declare -rA LINKS=(
	["../styles"]="/"
	["/tmp/talvos"]="/@fs/home/seth/Code/src/github.com/sethp/learn-gpgpu/tmp/_talvos"
)

mkdir -p public
for TARGET in ${!LINKS[@]}; do
	DEST=${LINKS[$TARGET]#/}

	BASEDIR=${DEST%/*}
	[ -n "$BASEDIR" ] && mkdir -p "public/$BASEDIR"

	ln -s "$TARGET" "public/${DEST}"
done
EOS

#  http://localhost:3000/@fs/home/seth/Code/src/github.com/sethp/learn-gpgpu/tmp/_talvos/lib/talvos/Block.cpp

# TODO[seth]: ./tmp/_talvos_cpy is sourced from
# `cp -r tmp/_talvos/{include,lib,tools/talvos-cmd} tmp/_talvos_cpy/`
RUN \
	--mount=type=bind,source=astro,target=/app/astro \
	--mount=type=bind,source=content,target=/app/content \
	--mount=type=bind,source=lib,target=/app/lib \
	--mount=type=bind,source=pages,target=/app/pages \
	--mount=type=bind,source=styles,target=/app/styles \
	--mount=type=bind,source=wasm,target=/app/wasm \
	--mount=type=bind,source=./astro.config.ts,target=/app/astro.config.ts \
	--mount=type=bind,source=./tsconfig.json,target=/app/tsconfig.json \
	--mount=type=bind,source=./tmp/_talvos_cpy,target=/tmp/talvos \
	pnpm run astro build

# Post-fixups
RUN --mount=type=bind,source=wasm,target=/app/wasm <<EOS
#!/bin/bash

set -euxo pipefail

for WASM_FILE in dist/_astro/*.wasm ; do
	BASE=${WASM_FILE##dist/_astro/}
	HASH=${BASE%.wasm}
	HASH=${HASH#*.}
	NAME=${BASE%."${HASH}".wasm}
	ORIG=${NAME}.wasm

	[ -f "wasm/$ORIG.dwp" ] && \
		cp "wasm/$ORIG.dwp" "dist/_astro/$NAME.$HASH.wasm.dwp"
done
EOS

FROM scratch
COPY --from=build /app/dist /
